package com.revature.presentation;

public enum UserMenuResult {
	APPLY_FOR_BANK_ACCOUNT, VIEW_BALANCE, PERFORM_TRANSACTION,
	VIEW_TRANSACTION_HISTORY,EDIT_CUSTOMER_DATA, ASSIGN_PRIMARY_ACCOUNT,
	LOG_OUT, QUIT_PROGRAM,LOGIN_AS_EMPLOYEE;
}
